Feature: Verify legitimate Targets can be loaded against the public TAS

  This feature ensures that target data located on an S3 bucket
  (expected to have been generated by XChem-Align)
  can be loaded into a new stack against the public proposal.
  We rely on a clean stack and a CAS-authenticated user.

  The steps rely on 'sensitive' material that is expected to be provided
  by environment variables. The tests will alert if these are not set.

  Background: Start with a new (empty) stack

    Create a new (up to date) stack and pass-in some important extra variables
    using the step's 'doc string'. The doc string, if set, is interpreted
    as JSON and the variables defined in it will be passed to the AWX template.

    Given an empty behaviour stack tagged latest
      """
      {
        "stack_disable_restrict_proposals_to_membership": "yes"
      }
      """
    Then the landing page response should be OK

  @wip
  Scenario Template: Load public targets

    Load target files (located in an S3 bucket) into the stack.
    The target files are expected to be in a TGZ format.
    We check the upload status and subsequent API responses.
    We introduce a timeout to allow for the upload to complete,
    which is typically twice the expected processing time (after upload).

    Given I can login to the behaviour stack
    And I can access the im-xchem-data bucket
    When I get the TGZ encoded file <tgz> from the bucket
    And I load it against target access string lb18145-1
    Then the API response should be ACCEPTED
    And I should get a Task status endpoint
    And the Task status should have a value of SUCCESS within <timeout> minutes
    When I call /api/target_experiment_uploads
    Then the length of the returned list should be 1
    When I call /api/targets?title=<target>
    Then the length of the returned list should be 1

    Examples: Public targets
    | tgz                                 | target    | timeout |
    | lb32627-66_v2.2_upload_1_2024-12_09 | A71EV2A   | 7       |
    | lb32633-6_v2.2_upload_1_2024-11-22  | CHIKV_Mac | 16      |
