---
name: latest stack test

on:
  push:
    branches:
    - main
  schedule:
  - cron: '35 6 * * *'
  workflow_dispatch:

jobs:
  test-alan:

    # We have to avoid Python 3.12 (3.12.8) as the GitHub Action
    # always generates an argparse error when we try and run
    # the awx command from within the 'behave' tests.
    strategy:
      matrix:
        python-version:
        - '3.11'

    runs-on: ubuntu-latest
    environment: behaviour-stack-alan

    steps:

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        virtualenvs-path: .venv
        installer-parallel: true

    - name: Install Dependencies
      run: poetry install --no-interaction --with dev

    - name: Static Analysis
      run: |
        source .venv/bin/activate
        pre-commit run --all-files

    # Dry-run the behaviour tests.
    # This checks that the tests and steps are syntactically correct,
    # crucially checking for missing steps.
    #
    # We do not run 'Work in Progress' (WIP) tests
    # (i.e. tests tagged with @wip).
    - name: Behaviour Tests (Dry Run)
      working-directory: ./behaviour
      run: |
        source ../.venv/bin/activate
        behave --tags=-wip --dry-run

    # We do not run 'Work in Progress' (WIP) tests
    # (i.e. tests tagged with @wip).
    - name: Behaviour Tests
      working-directory: ./behaviour
      run: |
        source ../.venv/bin/activate
        playwright install
        behave --tags=-wip
      env:
        BEHAVIOUR_AWS_ACCESS_KEY_ID: ${{ secrets.BEHAVIOUR_AWS_ACCESS_KEY_ID }}
        BEHAVIOUR_AWS_SECRET_ACCESS_KEY: ${{ secrets.BEHAVIOUR_AWS_SECRET_ACCESS_KEY }}
        BEHAVIOUR_AWS_ENDPOINT_URL: ${{ secrets.BEHAVIOUR_AWS_ENDPOINT_URL }}
        BEHAVIOUR_AWX_HOST: ${{ secrets.BEHAVIOUR_AWX_HOSTNAME }}
        BEHAVIOUR_AWX_USERNAME: ${{ secrets.BEHAVIOUR_AWX_USERNAME }}
        BEHAVIOUR_AWX_PASSWORD: ${{ secrets.BEHAVIOUR_AWX_PASSWORD }}
        BEHAVIOUR_STACK_NAME: behaviour
        BEHAVIOUR_STACK_USERNAME: ${{ secrets.BEHAVIOUR_STACK_USERNAME }}
        BEHAVIOUR_STACK_PASSWORD: ${{ secrets.BEHAVIOUR_STACK_PASSWORD }}
        BEHAVIOUR_STACK_CLIENT_ID_SECRET: ${{ secrets.BEHAVIOUR_STACK_CLIENT_ID_SECRET }}
