---
name: latest stack test

on:
  push:
    branches:
    - main

jobs:
  test-alan:
    strategy:
      matrix:
        python-version:
        - '3.12'

    runs-on: ubuntu-latest
    environment: behaviour-stack-alan
    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        virtualenvs-path: .venv
        installer-parallel: true
    - name: Install Dependencies
      run: poetry install --no-interaction --with dev
    - name: Static Analysis
      run: |
        source .venv/bin/activate
        pre-commit run --all-files
    - name: Behaviour Tests
      working-directory: ./bdd
      run: |
        source ../.venv/bin/activate
        behave
      env:
        BEHAVIOUR_AWX_HOSTNAME: ${{ secrets.BEHAVIOUR_AWX_HOSTNAME }}
        BEHAVIOUR_AWX_USERNAME: ${{ secrets.BEHAVIOUR_AWX_USERNAME }}
        BEHAVIOUR_AWX_PASSWORD: ${{ secrets.BEHAVIOUR_AWX_PASSWORD }}
