---
name: latest stack test

on:
  push:
    branches:
    - main
  schedule:
  - cron: '35 6 * * *'

jobs:
  test-alan:

    # We have to avoid Python 3.12 (3.12.8) as the GitHub Action
    # always generates an argparse error when we try and run
    # the awx command from within the 'behave' tests.
    strategy:
      matrix:
        python-version:
        - '3.11'

    runs-on: ubuntu-latest
    environment: behaviour-stack-alan

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        virtualenvs-path: .venv
        installer-parallel: true
    - name: Install Dependencies
      run: poetry install --no-interaction --with dev
    - name: Static Analysis
      run: |
        source .venv/bin/activate
        pre-commit run --all-files
    - name: Behaviour Tests
      working-directory: ./bdd
      run: |
        source ../.venv/bin/activate
        behave
      env:
        CONTROLLER_HOST: https://${{ secrets.BEHAVIOUR_AWX_HOSTNAME }}
        CONTROLLER_USERNAME: ${{ secrets.BEHAVIOUR_AWX_USERNAME }}
        CONTROLLER_PASSWORD: ${{ secrets.BEHAVIOUR_AWX_PASSWORD }}
